server:
  port: 8080
spring:
  application:
    name: common-service
  cloud:
    consul:
      host: 10.45.9.233 # consul ip
      port: 8500 #consul http端口
      discovery:
        enabled: true # 是否开启服务发现
        register: true # 是否将服务注册到Consul集群中心
        service-name:  xin-${spring.application.name}-${server.port}
        health-check-path: /${spring.application.name}/health
        health-check-interval: 15s #健康检查时间间隔
        tags: url-prefix-/${spring.application.name} #tag
        instance-id: ${spring.application.name}:${server.port} #注册的实例id