server:
  port: 10010
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#    register-with-eureka: false #不注册自己
#    fetch-registry: false #不拉取服务列表
zuul:
  # 路由前缀
#  prefix: /demo
  routes:
    # 要路由的服务: 映射地址     ->面向服务的路由
    # spring.application.name: /服务前缀/RequestMapping地址
    common-service: /common-service/**
hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetries: 0 # 同一实例的重试次数
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
