server:
  port: 10010
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/common/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
    consul:
      host: 10.45.4.22 #127.0.0.1 # consul ip 网络原因可能导致健康检查失败
      port: 8500 #consul http端口
      discovery:
        enabled: true # 是否开启服务发现
        register: true # 是否将服务注册到Consul集群中心
        service-name:  xin-${spring.application.name}-${server.port}
        health-check-path: /${spring.application.name}/health
        health-check-interval: 15s #健康检查时间间隔
        tags: url-prefix-/${spring.application.name} #tag
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port} #注册的实例id

        prefer-ip-address: true



